import XCTest
@testable import Runner

/// v0.3 Stage 0c wave 3C — Swift-side cross-platform IBLT parity.
///
/// Reads the fixture committed at
/// `resqmesh_app/test/fixtures/iblt_swift_parity_vectors.json` (the Dart
/// IBLT is the oracle; the fixture is regenerated by
/// `tool/generate_iblt_swift_parity_fixture.dart`) and asserts that the
/// Swift IBLT produces byte-identical bucket state for every case.
///
/// If this test fails after a change to either ios/Runner/IBLT.swift or
/// lib/app/mesh/iblt.dart, the cross-platform sync layer is broken —
/// spec docs/specs/native_transport_v1_2026-05-13.md §3.2.1 requires
/// bit-identical bucket bytes between Dart, Kotlin, and Swift.
final class IBLTParityTests: XCTestCase {

    /// Locate the fixture by walking up from this source file. Avoids
    /// needing Xcode bundle resource setup for the JSON file.
    private func loadFixture() throws -> [String: Any] {
        let thisFile = URL(fileURLWithPath: #file)
        // ios/RunnerTests/IBLTParityTests.swift → resqmesh_app/...
        let resqmeshAppRoot = thisFile
            .deletingLastPathComponent()    // RunnerTests
            .deletingLastPathComponent()    // ios
            .deletingLastPathComponent()    // resqmesh_app
        let fixtureURL = resqmeshAppRoot
            .appendingPathComponent("test")
            .appendingPathComponent("fixtures")
            .appendingPathComponent("iblt_swift_parity_vectors.json")
        let data = try Data(contentsOf: fixtureURL)
        guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw NSError(domain: "IBLTParityTests", code: 1,
                          userInfo: [NSLocalizedDescriptionKey: "fixture is not a JSON object"])
        }
        return json
    }

    func testFixtureMetadataMatchesLiveConstants() throws {
        let fixture = try loadFixture()
        XCTAssertEqual(fixture["bucket_count"] as? Int, IBLT.bucketCount)
        XCTAssertEqual(fixture["bucket_size"] as? Int, IBLT.bucketSize)
        XCTAssertEqual(fixture["total_bytes"] as? Int, IBLT.totalBytes)
        XCTAssertEqual(fixture["version"] as? Int, 1)
    }

    func testInsertRemoveCasesMatchFixture() throws {
        let fixture = try loadFixture()
        guard let cases = fixture["cases"] as? [[String: Any]] else {
            XCTFail("fixture has no cases array"); return
        }
        for c in cases {
            guard let insert = c["insert"] as? [String] else { continue }
            let remove = (c["remove"] as? [String]) ?? []
            let expectedHex = c["expected_bytes_hex"] as? String ?? ""
            let name = (c["name"] as? String) ?? "?"

            let iblt = IBLT()
            for id in insert { iblt.insert(id) }
            for id in remove { iblt.remove(id) }
            let bytes = iblt.toBytes()
            XCTAssertEqual(bytes.count, IBLT.totalBytes,
                           "case \(name) byte length mismatch")
            XCTAssertEqual(toHex(bytes), expectedHex,
                           "case \(name) diverged from Dart fixture — Swift IBLT is not bit-identical")
        }
    }

    func testSubtractCaseMatchesFixture() throws {
        let fixture = try loadFixture()
        guard let cases = fixture["cases"] as? [[String: Any]],
              let sub = cases.first(where: { ($0["name"] as? String) == "subtract_symmetric_diff_4" })
        else {
            XCTFail("subtract case missing from fixture"); return
        }
        let aInsert = sub["a_insert"] as? [String] ?? []
        let bInsert = sub["b_insert"] as? [String] ?? []
        let aHex = sub["a_bytes_hex"] as? String ?? ""
        let bHex = sub["b_bytes_hex"] as? String ?? ""
        let diffHex = sub["diff_bytes_hex"] as? String ?? ""

        let a = IBLT()
        let b = IBLT()
        for id in aInsert { a.insert(id) }
        for id in bInsert { b.insert(id) }
        XCTAssertEqual(toHex(a.toBytes()), aHex, "A bytes diverged")
        XCTAssertEqual(toHex(b.toBytes()), bHex, "B bytes diverged")
        XCTAssertEqual(toHex(a.subtract(b).toBytes()), diffHex,
                       "A.subtract(B) bytes diverged")
    }

    func testFromBytesRoundTrip() throws {
        let iblt = IBLT()
        for id in ["a", "b", "c", "d", "e"] { iblt.insert(id) }
        let bytes = iblt.toBytes()
        let restored = try IBLT.fromBytes(bytes)
        XCTAssertEqual(toHex(restored.toBytes()), toHex(bytes))
        for i in 0..<IBLT.bucketCount {
            XCTAssertEqual(restored.buckets[i].count, iblt.buckets[i].count, "bucket \(i) count")
            XCTAssertEqual(restored.buckets[i].keySum, iblt.buckets[i].keySum, "bucket \(i) keySum")
            XCTAssertEqual(restored.buckets[i].hashSum, iblt.buckets[i].hashSum, "bucket \(i) hashSum")
        }
    }

    func testEmptyIBLTIsAllZero() {
        let iblt = IBLT()
        XCTAssertEqual(iblt.toBytes().count, IBLT.totalBytes)
        for byte in iblt.toBytes() {
            XCTAssertEqual(byte, 0)
        }
    }

    func testSelfSubtractIsAllZero() {
        let a = IBLT()
        for id in ["x", "y", "z"] { a.insert(id) }
        let z = a.subtract(a)
        for byte in z.toBytes() {
            XCTAssertEqual(byte, 0)
        }
    }

    // MARK: - Bloom helpers parity

    func testBloomMagicDetection() {
        XCTAssertTrue(BlePlugin.hasBloomMagic([0xFF, 0xBF, 0x02, 0x00, 0x01, 0x02]))
        XCTAssertFalse(BlePlugin.hasBloomMagic([0xFF, 0xBE, 0x02, 0x00]))
        XCTAssertFalse(BlePlugin.hasBloomMagic([0xFF])) // too short
    }

    func testBloomMayContainSelfInsertedHits() {
        // Build a bit-vector identical to Android's buildBitVectorBloom:
        // 4B magic + 2048B bits, BLOOM_HASH_COUNT=7.
        let bloomSize = 2048
        let hashCount: UInt32 = 7
        var bits = [UInt8](repeating: 0, count: 4 + bloomSize)
        bits[0] = 0xFF; bits[1] = 0xBF; bits[2] = 0x02; bits[3] = 0x00
        let ids = ["evt-aaa", "evt-bbb", "evt-ccc"]
        let totalBits = UInt32(bloomSize * 8)
        for id in ids {
            for i in 0..<hashCount {
                let idx = Int(BlePlugin.bloomMurmurHash(id, seed: i) % totalBits)
                bits[4 + (idx >> 3)] |= UInt8(1 << (idx & 7))
            }
        }
        for id in ids {
            XCTAssertTrue(BlePlugin.bloomMayContain(bits, eventId: id), "\(id) should hit")
        }
        // A random unlikely ID — false negatives only, no guarantee of false
        // positives — assert at least one of several unlikely IDs misses.
        let unlikely = ["zz-1", "zz-2", "zz-3", "zz-4", "zz-5"]
        let anyMiss = unlikely.contains { !BlePlugin.bloomMayContain(bits, eventId: $0) }
        XCTAssertTrue(anyMiss, "bloom should miss at least one of \(unlikely)")
    }

    // MARK: - helpers

    private func toHex(_ bytes: Data) -> String {
        return bytes.map { String(format: "%02x", $0) }.joined()
    }
}
